package Enums;

import java.io.Serializable;

/**
 *
 * @author madsh
 */
public enum RequestArgumentName implements Serializable {
    USER_ID,
    PROFILE_ID,
    PROFILE_LIST_OF_CHANGES,
    PROFILE_LIST_OF_TABLE_FIELDS,
    PROFILE_GYM,
    PROFILE_CITY,
    PROFILE_AGE,
    PROFILE_FIRST_NAME,
    PROFILE_LAST_NAME,
    PROFILE_GENDER,
    PROFILE_COUNTRY,
    PROFILE_ACTIVE_BUDDY,
    PROGRAM_ID,
    PROGRAM_OWNER_ID,
    PROGRAM_DESCRIPTION,
    STAT_ID,
    USERNAME,
    PASSWORD,
    FIRST_NAME,
    LAST_NAME,
    TEXT,
    SEARCH_TYPE,
    EXERCISE,
    EXERCISE_ID,
    EXERCISE_NAME,
    EXERCISE_REPS,
    EXERCISE_WEIGHT,
    EXERCISE_TIME,
    PROGRAM_NAME,
    PROGRAM_ID,
    PROGRAM_TIME_TAKEN,
    PROGRAM_DATE,
    SENDER_ID,
    RECIVER_ID,
    INDEX,
    MESSAGE,
    BUDDY,
    STATS,
    SET_INFO,
    SET_ID
}