package Enums;

import java.io.Serializable;

/**
 *
 * @author madsh
 */
public enum RequestType implements Serializable {
    LOGIN,
    LOGOUT,
    CREATE_NEW_USER,
    SEARCH,
    GET_PROFILE,
    UPDATE_PROFILE,
    UPDATE_PASSWORD,
    UPDATE_USERNAME,
    DELETE_ACCOUNT,
    FOLLOW_PROFILE,
    FOLLOW_TRAINING_PROGRAM,
    SEND_BUDDY_REQUEST,
    ACCEPT_BUDDY_REQUEST,
    DENNY_BUDDY_REQUEST,
    IS_BUDDY,
    GET_ALL_BUDDYS,
    SET_GOAL,
    SET_STAT,
    REMOVE_STAT,
    SEND_MESSAGE,
    RECEIVE_MESSAGE_HISTORY,
    CREATE_TRAINING_PROGRAM,
    RECEIVE_EXERCISE,
    CREATE_EXERCISE,
    ADD_EXERCISE,
    REMOVE_EXERCISE,
    LOAD_ALL_EXERCISE,
    REMOVE_EXERCISE_FOR_TODAY,
    LOAD_ALL_STATS,
    GET_STATS,
    UPDATE_EXERCISE_INDEX,
    ADD_SET_TO_EXERCISE,
    UPDATE_SET_INDEX,
    REMOVE_SET,
    REMOVE_TRAINING_PROGRAM,
    GET_ALL_TRAINING_PROGRAMS,
    UPDATE_PROGRAM_INFO
}