CREATE TABLE buddys (profileid int4 NOT NULL, profileid2 int4 NOT NULL, active_buddy bool DEFAULT '0' NOT NULL, PRIMARY KEY (profileid, profileid2));
COMMENT ON COLUMN buddys.active_buddy IS 'This is to see if the people are buddys or not. If they have been boddy has been dismissed then you still need to be able to see there interactions and the like.';
CREATE TABLE exercise (id SERIAL NOT NULL, name varchar(255) DEFAULT 'Give me a name so i can be found' NOT NULL, description varchar(1000) DEFAULT 'If you cant tell by the name to bad someone did not give a description' NOT NULL, time_taken int8 DEFAULT -1 NOT NULL, rebs int4 DEFAULT -1 NOT NULL, sets int4 DEFAULT -1 NOT NULL, weight int4 DEFAULT -1 NOT NULL, PRIMARY KEY (id));
CREATE TABLE goal (id SERIAL NOT NULL, profileid int4 NOT NULL, weight int4 DEFAULT -1 NOT NULL, goal_text varchar(255) DEFAULT 'Why do I need a goal? I am to good to set a goal.' NOT NULL, PRIMARY KEY (id));
CREATE TABLE login (id SERIAL NOT NULL, username varchar(255) NOT NULL, hash_password bytea NOT NULL, password_salt bytea NOT NULL, PRIMARY KEY (id));
CREATE TABLE message (id SERIAL NOT NULL, sender int4 NOT NULL, receiver int4 NOT NULL, message varchar(1023) NOT NULL, time timestamp NOT NULL, "date" date NOT NULL, PRIMARY KEY (id));
CREATE TABLE profile (id SERIAL NOT NULL, login_id int4 NOT NULL, gym varchar(255) DEFAULT 'None' NOT NULL, city varchar(255) DEFAULT 'No city' NOT NULL, age int4 DEFAULT 200 NOT NULL, first_name varchar(255) DEFAULT 'john' NOT NULL, last_name varchar(255) DEFAULT 'doe' NOT NULL, gender varchar(255) DEFAULT 'No gender' NOT NULL, country varchar(255) DEFAULT 'Country of nowhere' NOT NULL, PRIMARY KEY (id));
CREATE TABLE question_for_buddys (id SERIAL NOT NULL, train_with_them bool DEFAULT '0' NOT NULL, what_do_i_train varchar(255) DEFAULT 'Why would i train anything' NOT NULL, experience varchar(255) DEFAULT 'new' NOT NULL, profileid int4 NOT NULL, PRIMARY KEY (id));
COMMENT ON COLUMN question_for_buddys.what_do_i_train IS 'I train some stuff';
COMMENT ON COLUMN question_for_buddys.experience IS 'Are you new to the gym or exercise. Or do you know what you are doing?';
CREATE TABLE scheme (id SERIAL NOT NULL, name varchar(255) DEFAULT 'No name' NOT NULL, description varchar(255) DEFAULT 'No description' NOT NULL, PRIMARY KEY (id));
CREATE TABLE scheme_profile (scheduleid int4 NOT NULL, profileid int4 NOT NULL, PRIMARY KEY (scheduleid, profileid));
CREATE TABLE scheme_training_program (training_programid int4 NOT NULL, scheduleid int4 NOT NULL, day varchar(255) DEFAULT 'No day' NOT NULL, PRIMARY KEY (training_programid, scheduleid));
CREATE TABLE stats (id SERIAL NOT NULL, profileid int4 NOT NULL, exerciseid int4 NOT NULL, time_taken int8 DEFAULT -1 NOT NULL, rebs int4 DEFAULT -1 NOT NULL, sets int4 DEFAULT -1 NOT NULL, weight int4 DEFAULT -1 NOT NULL, "date" date NOT NULL, PRIMARY KEY (id));
CREATE TABLE token (token uuid NOT NULL, logInid int4 NOT NULL);
CREATE TABLE training_program (id SERIAL NOT NULL, name varchar(255) DEFAULT 'No name' NOT NULL, description varchar(255) DEFAULT 'No Description' NOT NULL, PRIMARY KEY (id));
CREATE TABLE training_program_exercise (exerciseid int4 NOT NULL, training_programid int4 NOT NULL, PRIMARY KEY (exerciseid, training_programid));
CREATE TABLE tranings_hours (id SERIAL NOT NULL, day varchar(255) DEFAULT 'No day' NOT NULL, starting_time time(7) DEFAULT '16:40' NOT NULL, end_time time(7) DEFAULT '18:00' NOT NULL, Question_for_buddysid int4 NOT NULL, PRIMARY KEY (id));
COMMENT ON COLUMN tranings_hours.day IS 'Day you train';
CREATE INDEX login_id ON login (id);
CREATE UNIQUE INDEX login_username ON login (username);
CREATE INDEX login_hash_password ON login (hash_password);
CREATE INDEX login_password_salt ON login (password_salt);
CREATE INDEX scheme_training_program_day ON scheme_training_program (day);
CREATE INDEX stats_profileid ON stats (profileid);
CREATE INDEX stats_exerciseid ON stats (exerciseid);
ALTER TABLE buddys ADD CONSTRAINT FKbuddys967094 FOREIGN KEY (profileid) REFERENCES profile (id);
ALTER TABLE buddys ADD CONSTRAINT FKbuddys740159 FOREIGN KEY (profileid2) REFERENCES profile (id);
ALTER TABLE profile ADD CONSTRAINT FKprofile488694 FOREIGN KEY (login_id) REFERENCES login (id);
ALTER TABLE stats ADD CONSTRAINT FKstats65934 FOREIGN KEY (profileid) REFERENCES profile (id);
ALTER TABLE training_program_exercise ADD CONSTRAINT FKtraining_p855275 FOREIGN KEY (training_programid) REFERENCES training_program (id);
ALTER TABLE training_program_exercise ADD CONSTRAINT FKtraining_p194169 FOREIGN KEY (exerciseid) REFERENCES exercise (id);
ALTER TABLE stats ADD CONSTRAINT FKstats911505 FOREIGN KEY (exerciseid) REFERENCES exercise (id);
ALTER TABLE scheme_training_program ADD CONSTRAINT FKscheme_tra313403 FOREIGN KEY (scheduleid) REFERENCES scheme (id);
ALTER TABLE scheme_training_program ADD CONSTRAINT FKscheme_tra889963 FOREIGN KEY (training_programid) REFERENCES training_program (id);
ALTER TABLE scheme_profile ADD CONSTRAINT FKscheme_pro761813 FOREIGN KEY (scheduleid) REFERENCES scheme (id);
ALTER TABLE scheme_profile ADD CONSTRAINT FKscheme_pro981379 FOREIGN KEY (profileid) REFERENCES profile (id);
ALTER TABLE message ADD CONSTRAINT FKmessage3387 FOREIGN KEY (sender, receiver) REFERENCES buddys (profileid, profileid2);
ALTER TABLE tranings_hours ADD CONSTRAINT FKtranings_h999671 FOREIGN KEY (Question_for_buddysid) REFERENCES question_for_buddys (id);
ALTER TABLE question_for_buddys ADD CONSTRAINT FKquestion_f273342 FOREIGN KEY (profileid) REFERENCES profile (id);
ALTER TABLE goal ADD CONSTRAINT FKgoal645380 FOREIGN KEY (profileid) REFERENCES profile (id);
ALTER TABLE token ADD CONSTRAINT FKtoken86604 FOREIGN KEY (logInid) REFERENCES login (id);
